name: update resources
on: workflow_dispatch
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1

            - name: Fetch resources
              run: python3 championrate.py
              
            - name: check if here
              run: ls

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: riot/lol/resources/latest/en-US/championrates.json
                  commit-msg: Update resources
                  github-token: ${{ secrets.GITHUB_TOKEN }}
